import json
import re
import pandas as pd
from ollama import chat


# Review ontology candidates using a local LLM (Ollama)
def review_ontologies(
    ontology_candidates: pd.DataFrame,
    eurlex_chunks: pd.DataFrame,
    max_candidates: int,
    model: str,
    temperature: float,
    system_prompt: str,
    user_prompt_template: str,
    json_mode: bool,
) -> pd.DataFrame:

    # Store one review for each ontology candidate
    results = []

    # Process only the first max_candidates
    for _, row in ontology_candidates.head(max_candidates).iterrows():

        # Retrieve the original text chunk matching the candidate's chunk_id
        chunk = eurlex_chunks[
            eurlex_chunks["chunk_id"] == row["chunk_id"]
        ].iloc[0]

        # Build the prompt by inserting the ontology candidate
        user_prompt = user_prompt_template.format(
            ontology=row["ontology"],
            text=chunk["chunk_text"]
        )

        # Query the local LLM through Ollama
        response = chat(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": system_prompt,
                },
                {
                    "role": "user",
                    "content": user_prompt,
                },
            ],
            options={
                "temperature": temperature,
            },
            format="json" if json_mode else None,
        )

        # Extract the textual response
        review_text = response["message"]["content"]

        # Parse and validate the JSON returned by the LLM
        review_json = extract_json(review_text)

        # Save the review
        results.append(
            {
                "chunk_id": row["chunk_id"],
                "CELEX": row["CELEX"],

                # Original source legal text used as ground truth for the review
                "text": chunk["chunk_text"],

                # Original ontology generated by the first LLM
                "ontology": row["ontology"],

                # Review produced by the judge LLM
                "review": json.dumps(
                    review_json,
                    ensure_ascii=False,
                ),

                # Quick flag for later refinement stage
                "approved": review_json.get(
                    "approved",
                    False
                ),

                # Indicates if the ontology should be regenerated
                "revision_required": review_json.get(
                    "revision_required",
                    True
                ),
            }
        )

    # Return one review for each ontology candidate
    return pd.DataFrame(results)


# Helper to safely extract JSON from LLM output
def extract_json(text: str) -> dict:
    
    parsed_data = None

    # Handle empty or blank text responses
    if not text or text.strip() == "":
        return _build_fallback_json()

    # Strip Markdown code blocks (e.g., ```json ... ```) if present
    cleaned_text = re.sub(r"^```json\s*", "", text.strip(), flags=re.MULTILINE)
    cleaned_text = re.sub(r"^```\s*", "", cleaned_text, flags=re.MULTILINE)
    cleaned_text = re.sub(r"```$", "", cleaned_text, flags=re.MULTILINE).strip()

    # Attempt standard JSON decoding
    try:
        parsed_data = json.loads(cleaned_text)
    except json.JSONDecodeError:
        # Regex extraction fallback: Locate outermost curly braces
        match = re.search(r"\{.*\}", cleaned_text, re.DOTALL)
        if match:
            try:
                parsed_data = json.loads(match.group())
            except json.JSONDecodeError:
                pass

    # GUARDRAIL: Trigger fallback if JSON is invalid, not a dict, or empty ({})
    if not parsed_data or not isinstance(parsed_data, dict) or len(parsed_data) == 0:
        return _build_fallback_json()

    return parsed_data

# Generates a valid fallback JSON structure in case of parsing failures, empty model output ({}), or token truncation
def _build_fallback_json() -> dict:

    # Returns: dict: Standardized fallback review dictionary.    
    return {
        "overall_score": 3,
        "odrl_compliance": 3,
        "json_valid": True,
        "strengths": ["Procedural legal text or chunk processed"],
        "weaknesses": ["Text fragment is procedural or LLM output was empty/truncated"],
        "missing_concepts": [],
        "unsupported_concepts": [],
        "hallucinations": [],
        "suggested_amendments": [
            "Verify if procedural text requires structural ontology representation"
        ],
        "approved": False,
        "revision_required": True
    }